# Generated by Django 3.2.2 on 2021-05-08 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_groupnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=31, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.groupnames', verbose_name='group_key'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=31, verbose_name='surname'),
            preserve_default=False,
        ),
    ]
