# Generated by Django 3.2.2 on 2021-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210508_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.TextField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.TextField(max_length=32, verbose_name='surname'),
        ),
    ]
