# Generated by Django 3.2.2 on 2021-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_modelsnames_subjectsnames_tasksnames_themesnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonsNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonName', models.DateTimeField(verbose_name='Дата и время проведения пары')),
                ('TaskName', models.IntegerField(verbose_name='Номер пары')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
