# Generated by Django 3.2.2 on 2021-05-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_lessonsnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemesLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.lessonsnames', verbose_name='Lessons_key')),
                ('Theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.themesnames', verbose_name='Theme_key')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.subjectsnames', verbose_name='Subject_key')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Teacher_key')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.modelsnames', verbose_name='Module_key')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.subjectsnames', verbose_name='Subject_key')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.modelsnames', verbose_name='Module_key')),
                ('Theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.themesnames', verbose_name='Theme_key')),
            ],
        ),
        migrations.CreateModel(
            name='LessonsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.lessonsnames', verbose_name='Lessons_key')),
                ('Task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.tasksnames', verbose_name='Task_key')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.groupnames', verbose_name='Group_key')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.subjectsnames', verbose_name='Subject_key')),
            ],
        ),
    ]
