# Generated by Django 3.2.8 on 2021-10-24 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tasksstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='tasksnames',
            old_name='TaskName',
            new_name='max_score',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lessonsnames',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='brief',
            field=models.TextField(default='bried', max_length=1024, verbose_name='Описание задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='kind',
            field=models.CharField(default='kind', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.lessonsnames'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='name',
            field=models.CharField(default='name', max_length=64, verbose_name='Название задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='value',
            field=models.IntegerField(default=123, verbose_name='Ценнсть задания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.term')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.groupnames', verbose_name='group_key')),
            ],
        ),
        migrations.AddField(
            model_name='groupssubjects',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.term', verbose_name='term'),
        ),
        migrations.AddField(
            model_name='modelsnames',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.week'),
        ),
        migrations.AlterField(
            model_name='subjectsteachers',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.teacher', verbose_name='Teacher_key'),
        ),
        migrations.AlterField(
            model_name='tasksstudents',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.student', verbose_name='Students_key'),
        ),
    ]
