# Generated by Django 3.2.2 on 2021-11-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeks',
            name='Sem',
            field=models.IntegerField(default=1, verbose_name='Номер семестра'),
            preserve_default=False,
        ),
    ]
