# Generated by Django 3.2.8 on 2021-10-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211024_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksnames',
            name='brief',
            field=models.TextField(max_length=1024, null=True, verbose_name='Описание задания'),
        ),
    ]
