# Generated by Django 3.2.2 on 2021-11-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_weeks_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='Week1',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 1'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week10',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 10'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week11',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 11'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week12',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 12'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week13',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 13'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week14',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 14'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week15',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 15'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week16',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 16'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week2',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 2'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week3',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 3'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week4',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 4'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week5',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 5'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week6',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 6'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week7',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 7'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week8',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 8'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='Week9',
            field=models.CharField(max_length=255, null=True, verbose_name='Неделя 9'),
        ),
    ]
