# Generated by Django 3.2.2 on 2021-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20211114_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sem', models.IntegerField(verbose_name='Номер семестра')),
                ('Week1', models.CharField(max_length=255, null=True, verbose_name='Неделя 1')),
                ('Week2', models.CharField(max_length=255, null=True, verbose_name='Неделя 2')),
                ('Week3', models.CharField(max_length=255, null=True, verbose_name='Неделя 3')),
                ('Week4', models.CharField(max_length=255, null=True, verbose_name='Неделя 4')),
                ('Week5', models.CharField(max_length=255, null=True, verbose_name='Неделя 5')),
                ('Week6', models.CharField(max_length=255, null=True, verbose_name='Неделя 6')),
                ('Week7', models.CharField(max_length=255, null=True, verbose_name='Неделя 7')),
                ('Week8', models.CharField(max_length=255, null=True, verbose_name='Неделя 8')),
                ('Week9', models.CharField(max_length=255, null=True, verbose_name='Неделя 9')),
                ('Week10', models.CharField(max_length=255, null=True, verbose_name='Неделя 10')),
                ('Week11', models.CharField(max_length=255, null=True, verbose_name='Неделя 11')),
                ('Week12', models.CharField(max_length=255, null=True, verbose_name='Неделя 12')),
                ('Week13', models.CharField(max_length=255, null=True, verbose_name='Неделя 13')),
                ('Week14', models.CharField(max_length=255, null=True, verbose_name='Неделя 14')),
                ('Week15', models.CharField(max_length=255, null=True, verbose_name='Неделя 15')),
                ('Week16', models.CharField(max_length=255, null=True, verbose_name='Неделя 16')),
            ],
            options={
                'verbose_name': 'Семестры',
                'verbose_name_plural': 'Семестры',
            },
        ),
        migrations.DeleteModel(
            name='Weeks',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунты', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
