# Generated by Django 3.2.2 on 2021-11-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_semesterssubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksnames',
            name='TaskDescription',
            field=models.TextField(default=int, max_length=1024, verbose_name='Описание задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksnames',
            name='TaskMark',
            field=models.IntegerField(default=int, verbose_name='Максимальный балл за задание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksnames',
            name='TaskName',
            field=models.CharField(max_length=64, verbose_name='Название задания'),
        ),
    ]
