# Generated by Django 3.2.2 on 2021-11-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20211121_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectsmodules',
            options={'verbose_name': 'Связь: Предмет - Модуль', 'verbose_name_plural': 'Связь: Предмет - Модуль'},
        ),
        migrations.AlterField(
            model_name='subjectsmodules',
            name='Subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.subjectsnames'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ModulesNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(max_length=64, verbose_name='Название модуля')),
                ('subjects', models.ManyToManyField(blank=True, through='account.SubjectsModules', to='account.SubjectsNames')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.AlterField(
            model_name='modulethemes',
            name='Model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.modulesnames', verbose_name='Module_key'),
        ),
        migrations.AlterField(
            model_name='subjectsmodules',
            name='Module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.modulesnames'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModelsNames',
        ),
    ]
