# Generated by Django 3.2.2 on 2021-12-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20211121_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='Week1',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week10',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week11',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week12',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week13',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week14',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week15',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week16',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week2',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week3',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week4',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week5',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week6',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week7',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week8',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='Week9',
        ),
        migrations.AddField(
            model_name='semester',
            name='Week10_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя10_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week10_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя10_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week10_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя10_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week10_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя10_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week10_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя10_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week10_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя10_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week11_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя11_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week11_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя11_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week11_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя11_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week11_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя11_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week11_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя11_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week11_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя11_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week12_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя12_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week12_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя12_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week12_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя12_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week12_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя12_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week12_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя12_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week12_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя12_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week13_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя13_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week13_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя13_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week13_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя13_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week13_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя13_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week13_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя13_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week13_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя13_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week14_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя14_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week14_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя14_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week14_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя14_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week14_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя14_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week14_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя14_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week14_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя14_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week15_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя15_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week15_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя15_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week15_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя15_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week15_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя15_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week15_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя15_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week15_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя15_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week16_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя16_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week16_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя16_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week16_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя16_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week16_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя16_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week16_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя16_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week16_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя16_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week17_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя17_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week17_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя17_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week17_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя17_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week17_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя17_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week17_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя17_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week17_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя17_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week18_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя18_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week18_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя18_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week18_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя18_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week18_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя18_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week18_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя18_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week18_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя18_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week1_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя1_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week1_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя1_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week1_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя1_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week1_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя1_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week1_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя1_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week1_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя1_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week2_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя2_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week2_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя2_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week2_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя2_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week2_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя2_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week2_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя2_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week2_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя2_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week3_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя3_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week3_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя3_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week3_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя3_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week3_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя3_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week3_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя3_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week3_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя3_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week4_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя4_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week4_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя4_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week4_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя4_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week4_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя4_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week4_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя4_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week4_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя4_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week5_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя5_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week5_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя5_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week5_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя5_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week5_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя5_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week5_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя5_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week5_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя5_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week6_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя6_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week6_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя6_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week6_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя6_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week6_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя6_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week6_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя6_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week6_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя6_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week7_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя7_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week7_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя7_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week7_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя7_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week7_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя7_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week7_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя7_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week7_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя7_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week8_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя8_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week8_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя8_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week8_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя8_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week8_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя8_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week8_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя8_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week8_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя8_задание6'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week9_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя9_задание1'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week9_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя9_задание2'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week9_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя9_задание3'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week9_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя9_задание4'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week9_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя9_задание5'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Week9_6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Неделя9_задание6'),
        ),
    ]
